### ISSUE TITLE
[Bug]: Ollama endpoint not working

### ISSUE THREAD

**Issue by arsaboo** [Kuingsmile/word-GPT-Plus#70]
### 前置阅读 | Pre-reading

- [X] [Issues](https://github.com/Kuingsmile/word-gpt-plus/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [README](https://github.com/Kuingsmile/word-gpt-plus/blob/master/README.md)

### 服务类型 | Service Type

Self-hosted service

### 系统信息 | System Information

Mac(arm64)

### Office 版本 | Office Version

microsoft 365

### 问题重现 | Bug reproduce

Here's my docker compose:

```yaml
services:
  word-gpt-plus-service:
    image: kuingsmile/word-gpt-plus
    container_name: word_gpt_plus
    ports:
      - "3015:80"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"      
```    

I tried all the endpoints: http://host.docker.internal:11434/api/chat, http://host.docker.internal:11434 (or even the IP address of the machine on which Ollama is running)
![image](https://github.com/user-attachments/assets/0fa57376-fd4d-4eeb-a911-5e83370db05f)
